packages:
  - "apps/*"
  - "packages/*"
  - "!packages/ts-sdk"
  - "!packages/server-sdks/sdk-ruby"
  - "!packages/client-sdks/i18n-core"
  - "!packages/client-sdks/i18n-vue"
  - "!packages/client-sdks/i18n-svelte"
  - "!packages/client-sdks/i18n-angular"
  - "packages/client-sdks/*"
  - "packages/server-sdks/*"
